name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  # Group concurrency on workflow, then:
  # - Is merge run? Group `push` events
  # - Is pull request? Group `pull_request` events
  group: >-
    ${{ github.workflow }}-${{
      github.event_name == 'push'
        && github.base_ref
        || github.head_ref
    }}
  # Run merge runs in sequence. Cancel in progress pull request runs.
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.4
    with:
      parallel-commands: |
        yarn nx-cloud record -- yarn nx workspace-lint
        yarn nx-cloud record -- yarn nx format:check
      parallel-commands-on-agents: |
        yarn nx affected --target=lint --parallel=2
        yarn nx affected --target=test --parallel=2 --ci --code-coverage
        yarn nx affected --target=build --parallel=2
        yarn nx affected --target=e2e --parallel=1

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.4
    with:
      # The Free GitHub plan has a limit of 20 concurrent jobs on Ubuntu images
      # Reference: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
      # We optimize for 2 simultaneous workflow runs:
      # 2 x 1 main job   =  2 concurrent jobs
      # 2 x 9 agent jobs = 18 concurrent jobs
      # Total            = 20 concurrent jobs
      number-of-agents: 9
