name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

concurrency:
  # Group concurrency on workflow, then:
  # - Is merge run? Group on branch name (`refs/heads/main`)
  # - Is pull request? Group on pull request branch name, for example `feat/add-awesome-feature`
  group: >-
    ${{ github.workflow }}-${{
      github.event_name == 'push'
        && github.ref
        || github.head_ref
    }}
  # Run merge workflows in sequence to prevent parallel deployments and releases
  # Cancel stale pull request runs in progress for the same branch
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  # We're using Nx Cloud for Distributed Task Execution
  # Reference: https://nx.dev/using-nx/dte
  #
  # The coordinator outputs the combination of task outputs from the agents,
  # both terminal and file outputs
  dte_coordinator:
    name: DTE Coordinator
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.4
    with:
      # Commands run in parallel on this Nx Cloud coordinator
      parallel-commands: |
        yarn nx-cloud record -- yarn nx workspace-lint
        yarn nx-cloud record -- yarn nx format:check
      # Commands distributed between Nx Cloud agents
      parallel-commands-on-agents: |
        yarn nx affected --target=lint --parallel=2
        yarn nx affected --target=test --parallel=1 --ci --maxWorkers=2
        yarn nx affected --target=build --parallel=2 --exclude=ngworker-lumberjack,lumberjack-app
        yarn nx affected --target=e2e --parallel=1 --exclude=lumberjack-app-e2e
      final-commands: |
        yarn nx build ngworker-lumberjack
        yarn delete-path-alias @ngworker/lumberjack
        yarn delete-path-alias @ngworker/lumberjack/console-driver
        yarn delete-path-alias @ngworker/lumberjack/http-driver
        cp -r dist/libs/ngworker/lumberjack apps/lumberjack-app/node_modules/@ngworker/lumberjack
        yarn nx build lumberjack-app
        yarn nx e2e lumberjack-app-e2e

  # We're using Nx Cloud for Distributed Task Execution
  # Reference: https://nx.dev/using-nx/dte
  #
  # Agents receive tasks to execute in bulk whenever they are ready or finished
  # with previous tasks
  dte_agents:
    name: DTE Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.4
    with:
      # The Free GitHub plan has a limit of 20 concurrent jobs on Ubuntu images
      # Reference: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration
      # If we need to, we can optimize for 2 simultaneous workflow runs:
      # 2 x 1 main job   =  2 concurrent jobs
      # 2 x 9 agent jobs = 18 concurrent jobs
      # Total            = 20 concurrent jobs
      #
      # However, we don't have many projects or targets in this workspace, so we
      # lower the number of agents to reduce spent compute time.
      number-of-agents: 4
