name: Release NPM packages

env:
  NODE_OPTIONS: --max-old-space-size=6144
  NX_MAX_PARALLEL: 2

on:
  workflow_dispatch:
    inputs:
      release_as:
        type: 'choice'
        description: 'The release type. It can be one of: major, minor, patch, premajor, preminor, prepatch, or prerelease. Defaults to "patch"'
        required: true
        default: 'patch'
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease

jobs:
  release:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup git user to "🤖 NgWorker Bot"
        shell: bash
        run: git config user.email "-" && git config user.name "🤖 NgWorker Bot"

      - name: Release @ngworker/lumberjack
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx nx version ngworker-lumberjack --releaseAs=${{ github.event.inputs.release_as }} --preid=rc

      - name: Tag last-release
        shell: bash
        run: git tag -f last-release

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ inputs.github_token }}
          branch: ${{ github.ref }}
          force: true
          tags: true
